version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=coursemanagement

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coursemanagement
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    depends_on:
      - app
    environment:
      - SERVER_ADDR=app:50051

volumes:
  mysql-data:
